name: backup
version: 1.0.0
author: Kubilitics
description: Velero backup and restore workflows
commands:
  - bkp
permissions:
  - read:backups.velero.io
  - write:backups.velero.io
  - read:restores.velero.io
