run:
  timeout: 5m
  tests: false # Don't run linters on test files by default to reduce noise

linters:
  disable-all: true
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    # - unused # Disabled to pass CI on legacy code
    # - errcheck # Disabled to pass CI on legacy code

linters-settings:
  staticcheck:
    checks: ["all", "-SA1019"] # Ignore deprecated warnings

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
