// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/grpc/v1/cluster_data.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterStateEvent_EventType int32

const (
	ClusterStateEvent_UNKNOWN ClusterStateEvent_EventType = 0
	ClusterStateEvent_CREATE  ClusterStateEvent_EventType = 1
	ClusterStateEvent_UPDATE  ClusterStateEvent_EventType = 2
	ClusterStateEvent_DELETE  ClusterStateEvent_EventType = 3
)

// Enum value maps for ClusterStateEvent_EventType.
var (
	ClusterStateEvent_EventType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CREATE",
		2: "UPDATE",
		3: "DELETE",
	}
	ClusterStateEvent_EventType_value = map[string]int32{
		"UNKNOWN": 0,
		"CREATE":  1,
		"UPDATE":  2,
		"DELETE":  3,
	}
)

func (x ClusterStateEvent_EventType) Enum() *ClusterStateEvent_EventType {
	p := new(ClusterStateEvent_EventType)
	*p = x
	return p
}

func (x ClusterStateEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterStateEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_v1_cluster_data_proto_enumTypes[0].Descriptor()
}

func (ClusterStateEvent_EventType) Type() protoreflect.EnumType {
	return &file_api_grpc_v1_cluster_data_proto_enumTypes[0]
}

func (x ClusterStateEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterStateEvent_EventType.Descriptor instead.
func (ClusterStateEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{1, 0}
}

// StreamRequest configures the cluster state stream
type StreamRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClusterId       string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Namespaces      []string               `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`                                   // Empty = all namespaces
	ResourceTypes   []string               `protobuf:"bytes,3,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty"`        // Empty = all types (pods, nodes, services, etc.)
	IncludeMetadata bool                   `protobuf:"varint,4,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"` // Include full metadata or just essentials
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *StreamRequest) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *StreamRequest) GetResourceTypes() []string {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

func (x *StreamRequest) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

// ClusterStateEvent represents a single state change
type ClusterStateEvent struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	Type            ClusterStateEvent_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=kubilitics.backend.v1.ClusterStateEvent_EventType" json:"type,omitempty"`
	ResourceType    string                      `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // "Pod", "Node", "Service", etc.
	Namespace       string                      `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name            string                      `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Uid             string                      `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	ResourceVersion string                      `protobuf:"bytes,6,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	Timestamp       int64                       `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	Data            string                      `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`            // JSON-encoded resource data
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClusterStateEvent) Reset() {
	*x = ClusterStateEvent{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStateEvent) ProtoMessage() {}

func (x *ClusterStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStateEvent.ProtoReflect.Descriptor instead.
func (*ClusterStateEvent) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterStateEvent) GetType() ClusterStateEvent_EventType {
	if x != nil {
		return x.Type
	}
	return ClusterStateEvent_UNKNOWN
}

func (x *ClusterStateEvent) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ClusterStateEvent) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ClusterStateEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterStateEvent) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ClusterStateEvent) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *ClusterStateEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClusterStateEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// GetResourceRequest requests a single resource
type GetResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{2}
}

func (x *GetResourceRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *GetResourceRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *GetResourceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ResourceResponse contains a single resource
type ResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Uid           string                 `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Data          string                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"` // JSON-encoded resource
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceResponse) Reset() {
	*x = ResourceResponse{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceResponse) ProtoMessage() {}

func (x *ResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceResponse.ProtoReflect.Descriptor instead.
func (*ResourceResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceResponse) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ResourceResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ResourceResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// ListResourcesRequest lists resources
type ListResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"` // Empty = all namespaces
	LabelSelector map[string]string      `protobuf:"bytes,4,rep,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{4}
}

func (x *ListResourcesRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ListResourcesRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ListResourcesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListResourcesRequest) GetLabelSelector() map[string]string {
	if x != nil {
		return x.LabelSelector
	}
	return nil
}

// ListResourcesResponse contains multiple resources
type ListResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*ResourceResponse    `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{5}
}

func (x *ListResourcesResponse) GetResources() []*ResourceResponse {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ListResourcesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// TopologyRequest requests topology graph
type TopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"` // Empty = all namespaces
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyRequest) Reset() {
	*x = TopologyRequest{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyRequest) ProtoMessage() {}

func (x *TopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyRequest.ProtoReflect.Descriptor instead.
func (*TopologyRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{6}
}

func (x *TopologyRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *TopologyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// TopologyResponse contains topology graph
type TopologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*TopologyNode        `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*TopologyEdge        `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyResponse) Reset() {
	*x = TopologyResponse{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyResponse) ProtoMessage() {}

func (x *TopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyResponse.ProtoReflect.Descriptor instead.
func (*TopologyResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{7}
}

func (x *TopologyResponse) GetNodes() []*TopologyNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *TopologyResponse) GetEdges() []*TopologyEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type TopologyNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyNode) Reset() {
	*x = TopologyNode{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyNode) ProtoMessage() {}

func (x *TopologyNode) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyNode.ProtoReflect.Descriptor instead.
func (*TopologyNode) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{8}
}

func (x *TopologyNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TopologyNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TopologyNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopologyNode) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TopologyNode) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TopologyNode) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TopologyEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Relationship  string                 `protobuf:"bytes,3,opt,name=relationship,proto3" json:"relationship,omitempty"` // "owns", "uses", "routes_to", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyEdge) Reset() {
	*x = TopologyEdge{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyEdge) ProtoMessage() {}

func (x *TopologyEdge) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyEdge.ProtoReflect.Descriptor instead.
func (*TopologyEdge) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{9}
}

func (x *TopologyEdge) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *TopologyEdge) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *TopologyEdge) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

// HealthRequest requests cluster health
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{10}
}

func (x *HealthRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// HealthResponse contains cluster health
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "healthy", "degraded", "critical"
	HealthyNodes  int32                  `protobuf:"varint,2,opt,name=healthy_nodes,json=healthyNodes,proto3" json:"healthy_nodes,omitempty"`
	TotalNodes    int32                  `protobuf:"varint,3,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	HealthyPods   int32                  `protobuf:"varint,4,opt,name=healthy_pods,json=healthyPods,proto3" json:"healthy_pods,omitempty"`
	TotalPods     int32                  `protobuf:"varint,5,opt,name=total_pods,json=totalPods,proto3" json:"total_pods,omitempty"`
	Issues        []*HealthIssue         `protobuf:"bytes,6,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetHealthyNodes() int32 {
	if x != nil {
		return x.HealthyNodes
	}
	return 0
}

func (x *HealthResponse) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *HealthResponse) GetHealthyPods() int32 {
	if x != nil {
		return x.HealthyPods
	}
	return 0
}

func (x *HealthResponse) GetTotalPods() int32 {
	if x != nil {
		return x.TotalPods
	}
	return 0
}

func (x *HealthResponse) GetIssues() []*HealthIssue {
	if x != nil {
		return x.Issues
	}
	return nil
}

type HealthIssue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"` // "warning", "critical"
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthIssue) Reset() {
	*x = HealthIssue{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthIssue) ProtoMessage() {}

func (x *HealthIssue) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthIssue.ProtoReflect.Descriptor instead.
func (*HealthIssue) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{12}
}

func (x *HealthIssue) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *HealthIssue) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *HealthIssue) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *HealthIssue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HealthIssue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// MetricsRequest requests resource metrics
type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{13}
}

func (x *MetricsRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *MetricsRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *MetricsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MetricsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// MetricsResponse contains resource metrics
type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`          // millicores
	MemoryUsage   float64                `protobuf:"fixed64,5,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"` // bytes
	CpuLimit      float64                `protobuf:"fixed64,6,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryLimit   float64                `protobuf:"fixed64,7,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{14}
}

func (x *MetricsResponse) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *MetricsResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MetricsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricsResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *MetricsResponse) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *MetricsResponse) GetCpuLimit() float64 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *MetricsResponse) GetMemoryLimit() float64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *MetricsResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// EventsRequest requests Kubernetes events
type EventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"` // Max events to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsRequest) Reset() {
	*x = EventsRequest{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest) ProtoMessage() {}

func (x *EventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest.ProtoReflect.Descriptor instead.
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{15}
}

func (x *EventsRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *EventsRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *EventsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EventsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// EventsResponse contains Kubernetes events
type EventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsResponse) Reset() {
	*x = EventsResponse{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse) ProtoMessage() {}

func (x *EventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse.ProtoReflect.Descriptor instead.
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{16}
}

func (x *EventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "Normal", "Warning"
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{17}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// CommandRequest executes a command in a pod
type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName       string                 `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Container     string                 `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	Command       []string               `protobuf:"bytes,5,rep,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{18}
}

func (x *CommandRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *CommandRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CommandRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *CommandRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *CommandRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

// CommandResponse contains command output
type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_cluster_data_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_cluster_data_proto_rawDescGZIP(), []int{19}
}

func (x *CommandResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_api_grpc_v1_cluster_data_proto protoreflect.FileDescriptor

const file_api_grpc_v1_cluster_data_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/grpc/v1/cluster_data.proto\x12\x15kubilitics.backend.v1\"\xa0\x01\n" +
	"\rStreamRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x02 \x03(\tR\n" +
	"namespaces\x12%\n" +
	"\x0eresource_types\x18\x03 \x03(\tR\rresourceTypes\x12)\n" +
	"\x10include_metadata\x18\x04 \x01(\bR\x0fincludeMetadata\"\xdf\x02\n" +
	"\x11ClusterStateEvent\x12F\n" +
	"\x04type\x18\x01 \x01(\x0e22.kubilitics.backend.v1.ClusterStateEvent.EventTypeR\x04type\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\tR\x03uid\x12)\n" +
	"\x10resource_version\x18\x06 \x01(\tR\x0fresourceVersion\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04data\x18\b \x01(\tR\x04data\"<\n" +
	"\tEventType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06CREATE\x10\x01\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\"\x8a\x01\n" +
	"\x12GetResourceRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\x8f\x01\n" +
	"\x10ResourceResponse\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\tR\x03uid\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\"\xa1\x02\n" +
	"\x14ListResourcesRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12e\n" +
	"\x0elabel_selector\x18\x04 \x03(\v2>.kubilitics.backend.v1.ListResourcesRequest.LabelSelectorEntryR\rlabelSelector\x1a@\n" +
	"\x12LabelSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\x15ListResourcesResponse\x12E\n" +
	"\tresources\x18\x01 \x03(\v2'.kubilitics.backend.v1.ResourceResponseR\tresources\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"N\n" +
	"\x0fTopologyRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"\x88\x01\n" +
	"\x10TopologyResponse\x129\n" +
	"\x05nodes\x18\x01 \x03(\v2#.kubilitics.backend.v1.TopologyNodeR\x05nodes\x129\n" +
	"\x05edges\x18\x02 \x03(\v2#.kubilitics.backend.v1.TopologyEdgeR\x05edges\"\x88\x02\n" +
	"\fTopologyNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12M\n" +
	"\bmetadata\x18\x06 \x03(\v21.kubilitics.backend.v1.TopologyNode.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\fTopologyEdge\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\"\n" +
	"\frelationship\x18\x03 \x01(\tR\frelationship\".\n" +
	"\rHealthRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"\xec\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12#\n" +
	"\rhealthy_nodes\x18\x02 \x01(\x05R\fhealthyNodes\x12\x1f\n" +
	"\vtotal_nodes\x18\x03 \x01(\x05R\n" +
	"totalNodes\x12!\n" +
	"\fhealthy_pods\x18\x04 \x01(\x05R\vhealthyPods\x12\x1d\n" +
	"\n" +
	"total_pods\x18\x05 \x01(\x05R\ttotalPods\x12:\n" +
	"\x06issues\x18\x06 \x03(\v2\".kubilitics.backend.v1.HealthIssueR\x06issues\"\x9a\x01\n" +
	"\vHealthIssue\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x86\x01\n" +
	"\x0eMetricsRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\x86\x02\n" +
	"\x0fMetricsResponse\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tcpu_usage\x18\x04 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x05 \x01(\x01R\vmemoryUsage\x12\x1b\n" +
	"\tcpu_limit\x18\x06 \x01(\x01R\bcpuLimit\x12!\n" +
	"\fmemory_limit\x18\a \x01(\x01R\vmemoryLimit\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"\x9b\x01\n" +
	"\rEventsRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"F\n" +
	"\x0eEventsResponse\x124\n" +
	"\x06events\x18\x01 \x03(\v2\x1c.kubilitics.backend.v1.EventR\x06events\"\x81\x01\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\"\xa0\x01\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12\x1c\n" +
	"\tcontainer\x18\x04 \x01(\tR\tcontainer\x12\x18\n" +
	"\acommand\x18\x05 \x03(\tR\acommand\"^\n" +
	"\x0fCommandResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode2\xa9\x06\n" +
	"\x12ClusterDataService\x12f\n" +
	"\x12StreamClusterState\x12$.kubilitics.backend.v1.StreamRequest\x1a(.kubilitics.backend.v1.ClusterStateEvent0\x01\x12a\n" +
	"\vGetResource\x12).kubilitics.backend.v1.GetResourceRequest\x1a'.kubilitics.backend.v1.ResourceResponse\x12j\n" +
	"\rListResources\x12+.kubilitics.backend.v1.ListResourcesRequest\x1a,.kubilitics.backend.v1.ListResourcesResponse\x12c\n" +
	"\x10GetTopologyGraph\x12&.kubilitics.backend.v1.TopologyRequest\x1a'.kubilitics.backend.v1.TopologyResponse\x12_\n" +
	"\x10GetClusterHealth\x12$.kubilitics.backend.v1.HealthRequest\x1a%.kubilitics.backend.v1.HealthResponse\x12[\n" +
	"\n" +
	"GetMetrics\x12%.kubilitics.backend.v1.MetricsRequest\x1a&.kubilitics.backend.v1.MetricsResponse\x12X\n" +
	"\tGetEvents\x12$.kubilitics.backend.v1.EventsRequest\x1a%.kubilitics.backend.v1.EventsResponse\x12_\n" +
	"\x0eExecuteCommand\x12%.kubilitics.backend.v1.CommandRequest\x1a&.kubilitics.backend.v1.CommandResponseB6Z4github.com/kubilitics/kubilitics-backend/api/grpc/v1b\x06proto3"

var (
	file_api_grpc_v1_cluster_data_proto_rawDescOnce sync.Once
	file_api_grpc_v1_cluster_data_proto_rawDescData []byte
)

func file_api_grpc_v1_cluster_data_proto_rawDescGZIP() []byte {
	file_api_grpc_v1_cluster_data_proto_rawDescOnce.Do(func() {
		file_api_grpc_v1_cluster_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_v1_cluster_data_proto_rawDesc), len(file_api_grpc_v1_cluster_data_proto_rawDesc)))
	})
	return file_api_grpc_v1_cluster_data_proto_rawDescData
}

var file_api_grpc_v1_cluster_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_grpc_v1_cluster_data_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_grpc_v1_cluster_data_proto_goTypes = []any{
	(ClusterStateEvent_EventType)(0), // 0: kubilitics.backend.v1.ClusterStateEvent.EventType
	(*StreamRequest)(nil),            // 1: kubilitics.backend.v1.StreamRequest
	(*ClusterStateEvent)(nil),        // 2: kubilitics.backend.v1.ClusterStateEvent
	(*GetResourceRequest)(nil),       // 3: kubilitics.backend.v1.GetResourceRequest
	(*ResourceResponse)(nil),         // 4: kubilitics.backend.v1.ResourceResponse
	(*ListResourcesRequest)(nil),     // 5: kubilitics.backend.v1.ListResourcesRequest
	(*ListResourcesResponse)(nil),    // 6: kubilitics.backend.v1.ListResourcesResponse
	(*TopologyRequest)(nil),          // 7: kubilitics.backend.v1.TopologyRequest
	(*TopologyResponse)(nil),         // 8: kubilitics.backend.v1.TopologyResponse
	(*TopologyNode)(nil),             // 9: kubilitics.backend.v1.TopologyNode
	(*TopologyEdge)(nil),             // 10: kubilitics.backend.v1.TopologyEdge
	(*HealthRequest)(nil),            // 11: kubilitics.backend.v1.HealthRequest
	(*HealthResponse)(nil),           // 12: kubilitics.backend.v1.HealthResponse
	(*HealthIssue)(nil),              // 13: kubilitics.backend.v1.HealthIssue
	(*MetricsRequest)(nil),           // 14: kubilitics.backend.v1.MetricsRequest
	(*MetricsResponse)(nil),          // 15: kubilitics.backend.v1.MetricsResponse
	(*EventsRequest)(nil),            // 16: kubilitics.backend.v1.EventsRequest
	(*EventsResponse)(nil),           // 17: kubilitics.backend.v1.EventsResponse
	(*Event)(nil),                    // 18: kubilitics.backend.v1.Event
	(*CommandRequest)(nil),           // 19: kubilitics.backend.v1.CommandRequest
	(*CommandResponse)(nil),          // 20: kubilitics.backend.v1.CommandResponse
	nil,                              // 21: kubilitics.backend.v1.ListResourcesRequest.LabelSelectorEntry
	nil,                              // 22: kubilitics.backend.v1.TopologyNode.MetadataEntry
}
var file_api_grpc_v1_cluster_data_proto_depIdxs = []int32{
	0,  // 0: kubilitics.backend.v1.ClusterStateEvent.type:type_name -> kubilitics.backend.v1.ClusterStateEvent.EventType
	21, // 1: kubilitics.backend.v1.ListResourcesRequest.label_selector:type_name -> kubilitics.backend.v1.ListResourcesRequest.LabelSelectorEntry
	4,  // 2: kubilitics.backend.v1.ListResourcesResponse.resources:type_name -> kubilitics.backend.v1.ResourceResponse
	9,  // 3: kubilitics.backend.v1.TopologyResponse.nodes:type_name -> kubilitics.backend.v1.TopologyNode
	10, // 4: kubilitics.backend.v1.TopologyResponse.edges:type_name -> kubilitics.backend.v1.TopologyEdge
	22, // 5: kubilitics.backend.v1.TopologyNode.metadata:type_name -> kubilitics.backend.v1.TopologyNode.MetadataEntry
	13, // 6: kubilitics.backend.v1.HealthResponse.issues:type_name -> kubilitics.backend.v1.HealthIssue
	18, // 7: kubilitics.backend.v1.EventsResponse.events:type_name -> kubilitics.backend.v1.Event
	1,  // 8: kubilitics.backend.v1.ClusterDataService.StreamClusterState:input_type -> kubilitics.backend.v1.StreamRequest
	3,  // 9: kubilitics.backend.v1.ClusterDataService.GetResource:input_type -> kubilitics.backend.v1.GetResourceRequest
	5,  // 10: kubilitics.backend.v1.ClusterDataService.ListResources:input_type -> kubilitics.backend.v1.ListResourcesRequest
	7,  // 11: kubilitics.backend.v1.ClusterDataService.GetTopologyGraph:input_type -> kubilitics.backend.v1.TopologyRequest
	11, // 12: kubilitics.backend.v1.ClusterDataService.GetClusterHealth:input_type -> kubilitics.backend.v1.HealthRequest
	14, // 13: kubilitics.backend.v1.ClusterDataService.GetMetrics:input_type -> kubilitics.backend.v1.MetricsRequest
	16, // 14: kubilitics.backend.v1.ClusterDataService.GetEvents:input_type -> kubilitics.backend.v1.EventsRequest
	19, // 15: kubilitics.backend.v1.ClusterDataService.ExecuteCommand:input_type -> kubilitics.backend.v1.CommandRequest
	2,  // 16: kubilitics.backend.v1.ClusterDataService.StreamClusterState:output_type -> kubilitics.backend.v1.ClusterStateEvent
	4,  // 17: kubilitics.backend.v1.ClusterDataService.GetResource:output_type -> kubilitics.backend.v1.ResourceResponse
	6,  // 18: kubilitics.backend.v1.ClusterDataService.ListResources:output_type -> kubilitics.backend.v1.ListResourcesResponse
	8,  // 19: kubilitics.backend.v1.ClusterDataService.GetTopologyGraph:output_type -> kubilitics.backend.v1.TopologyResponse
	12, // 20: kubilitics.backend.v1.ClusterDataService.GetClusterHealth:output_type -> kubilitics.backend.v1.HealthResponse
	15, // 21: kubilitics.backend.v1.ClusterDataService.GetMetrics:output_type -> kubilitics.backend.v1.MetricsResponse
	17, // 22: kubilitics.backend.v1.ClusterDataService.GetEvents:output_type -> kubilitics.backend.v1.EventsResponse
	20, // 23: kubilitics.backend.v1.ClusterDataService.ExecuteCommand:output_type -> kubilitics.backend.v1.CommandResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_grpc_v1_cluster_data_proto_init() }
func file_api_grpc_v1_cluster_data_proto_init() {
	if File_api_grpc_v1_cluster_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_v1_cluster_data_proto_rawDesc), len(file_api_grpc_v1_cluster_data_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_v1_cluster_data_proto_goTypes,
		DependencyIndexes: file_api_grpc_v1_cluster_data_proto_depIdxs,
		EnumInfos:         file_api_grpc_v1_cluster_data_proto_enumTypes,
		MessageInfos:      file_api_grpc_v1_cluster_data_proto_msgTypes,
	}.Build()
	File_api_grpc_v1_cluster_data_proto = out.File
	file_api_grpc_v1_cluster_data_proto_goTypes = nil
	file_api_grpc_v1_cluster_data_proto_depIdxs = nil
}
