// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: cluster_data.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StateStreamRequest initiates a cluster state stream.
type StateStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of namespaces to watch (empty = all namespaces)
	Namespaces []string `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	// Resource kinds to watch (empty = all kinds)
	ResourceKinds []string `protobuf:"bytes,2,rep,name=resource_kinds,json=resourceKinds,proto3" json:"resource_kinds,omitempty"`
	// Label selectors for filtering
	LabelSelector map[string]string `protobuf:"bytes,3,rep,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Whether to include initial snapshot
	IncludeSnapshot bool `protobuf:"varint,4,opt,name=include_snapshot,json=includeSnapshot,proto3" json:"include_snapshot,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StateStreamRequest) Reset() {
	*x = StateStreamRequest{}
	mi := &file_cluster_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateStreamRequest) ProtoMessage() {}

func (x *StateStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateStreamRequest.ProtoReflect.Descriptor instead.
func (*StateStreamRequest) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{0}
}

func (x *StateStreamRequest) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *StateStreamRequest) GetResourceKinds() []string {
	if x != nil {
		return x.ResourceKinds
	}
	return nil
}

func (x *StateStreamRequest) GetLabelSelector() map[string]string {
	if x != nil {
		return x.LabelSelector
	}
	return nil
}

func (x *StateStreamRequest) GetIncludeSnapshot() bool {
	if x != nil {
		return x.IncludeSnapshot
	}
	return false
}

// StateUpdate represents a single cluster state update.
type StateUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Update type: ADDED, MODIFIED, DELETED, SNAPSHOT
	UpdateType string `protobuf:"bytes,1,opt,name=update_type,json=updateType,proto3" json:"update_type,omitempty"`
	// The resource being updated
	Resource *Resource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// Timestamp of the update
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Sequence number for ordering
	Sequence      int64 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateUpdate) Reset() {
	*x = StateUpdate{}
	mi := &file_cluster_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdate) ProtoMessage() {}

func (x *StateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdate.ProtoReflect.Descriptor instead.
func (*StateUpdate) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{1}
}

func (x *StateUpdate) GetUpdateType() string {
	if x != nil {
		return x.UpdateType
	}
	return ""
}

func (x *StateUpdate) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *StateUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StateUpdate) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// ResourceRequest requests a specific resource.
type ResourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource kind (e.g., "Pod", "Deployment")
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Namespace (empty for cluster-scoped resources)
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Resource name
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Cluster ID (for multi-cluster support)
	ClusterId     string `protobuf:"bytes,4,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	mi := &file_cluster_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// Resource represents a Kubernetes resource.
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource kind
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// API version
	ApiVersion string `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Namespace
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Name
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// UID
	Uid string `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	// Resource version
	ResourceVersion string `protobuf:"bytes,6,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	// Labels
	Labels map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Annotations
	Annotations map[string]string `protobuf:"bytes,8,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Raw YAML/JSON data
	Data []byte `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	// Creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Status (e.g., "Running", "Failed")
	Status string `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	// Owner references
	OwnerRefs     []*OwnerReference `protobuf:"bytes,12,rep,name=owner_refs,json=ownerRefs,proto3" json:"owner_refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_cluster_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{3}
}

func (x *Resource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Resource) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Resource) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Resource) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *Resource) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Resource) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Resource) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Resource) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Resource) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Resource) GetOwnerRefs() []*OwnerReference {
	if x != nil {
		return x.OwnerRefs
	}
	return nil
}

// OwnerReference represents a Kubernetes owner reference.
type OwnerReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uid           string                 `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Controller    bool                   `protobuf:"varint,4,opt,name=controller,proto3" json:"controller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnerReference) Reset() {
	*x = OwnerReference{}
	mi := &file_cluster_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnerReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnerReference) ProtoMessage() {}

func (x *OwnerReference) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnerReference.ProtoReflect.Descriptor instead.
func (*OwnerReference) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{4}
}

func (x *OwnerReference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OwnerReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OwnerReference) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *OwnerReference) GetController() bool {
	if x != nil {
		return x.Controller
	}
	return false
}

// ListRequest lists resources with optional filtering.
type ListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource kind
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Namespace (empty = all namespaces)
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Label selector
	LabelSelector map[string]string `protobuf:"bytes,3,rep,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Field selector
	FieldSelector map[string]string `protobuf:"bytes,4,rep,name=field_selector,json=fieldSelector,proto3" json:"field_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Cluster ID
	ClusterId string `protobuf:"bytes,5,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Pagination limit
	Limit int32 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	// Continuation token
	ContinueToken string `protobuf:"bytes,7,opt,name=continue_token,json=continueToken,proto3" json:"continue_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_cluster_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ListRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListRequest) GetLabelSelector() map[string]string {
	if x != nil {
		return x.LabelSelector
	}
	return nil
}

func (x *ListRequest) GetFieldSelector() map[string]string {
	if x != nil {
		return x.FieldSelector
	}
	return nil
}

func (x *ListRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetContinueToken() string {
	if x != nil {
		return x.ContinueToken
	}
	return ""
}

// ResourceList is a list of resources.
type ResourceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Resource            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	ContinueToken string                 `protobuf:"bytes,2,opt,name=continue_token,json=continueToken,proto3" json:"continue_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceList) Reset() {
	*x = ResourceList{}
	mi := &file_cluster_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceList) ProtoMessage() {}

func (x *ResourceList) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceList.ProtoReflect.Descriptor instead.
func (*ResourceList) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceList) GetItems() []*Resource {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ResourceList) GetContinueToken() string {
	if x != nil {
		return x.ContinueToken
	}
	return ""
}

func (x *ResourceList) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// CommandRequest executes a command against a resource.
type CommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation type: "restart", "scale", "rollback", "delete", etc.
	Operation string `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	// Target resource
	Target *Resource `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Operation parameters (JSON-encoded)
	Params []byte `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	// Dry run mode
	DryRun bool `protobuf:"varint,4,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	// Correlation ID for audit trail
	CorrelationId string `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_cluster_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{7}
}

func (x *CommandRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *CommandRequest) GetTarget() *Resource {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *CommandRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *CommandRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *CommandRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// CommandResult is the result of a command execution.
type CommandResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success or failure
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Result message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Error details (if failed)
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Updated resource state (if applicable)
	UpdatedResource *Resource `protobuf:"bytes,4,opt,name=updated_resource,json=updatedResource,proto3" json:"updated_resource,omitempty"`
	// Correlation ID
	CorrelationId string `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_cluster_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{8}
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetUpdatedResource() *Resource {
	if x != nil {
		return x.UpdatedResource
	}
	return nil
}

func (x *CommandResult) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// TopologyRequest requests a topology graph.
type TopologyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespace filter (empty = all)
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Root resource (for subtree queries)
	Root *ResourceRequest `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	// Maximum depth (0 = unlimited)
	MaxDepth int32 `protobuf:"varint,3,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	// Cluster ID
	ClusterId     string `protobuf:"bytes,4,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyRequest) Reset() {
	*x = TopologyRequest{}
	mi := &file_cluster_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyRequest) ProtoMessage() {}

func (x *TopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyRequest.ProtoReflect.Descriptor instead.
func (*TopologyRequest) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{9}
}

func (x *TopologyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TopologyRequest) GetRoot() *ResourceRequest {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *TopologyRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *TopologyRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// TopologyGraph represents a resource dependency graph.
type TopologyGraph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*ResourceNode        `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*Dependency          `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	TotalNodes    int32                  `protobuf:"varint,3,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	TotalEdges    int32                  `protobuf:"varint,4,opt,name=total_edges,json=totalEdges,proto3" json:"total_edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyGraph) Reset() {
	*x = TopologyGraph{}
	mi := &file_cluster_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyGraph) ProtoMessage() {}

func (x *TopologyGraph) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyGraph.ProtoReflect.Descriptor instead.
func (*TopologyGraph) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{10}
}

func (x *TopologyGraph) GetNodes() []*ResourceNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *TopologyGraph) GetEdges() []*Dependency {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *TopologyGraph) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *TopologyGraph) GetTotalEdges() int32 {
	if x != nil {
		return x.TotalEdges
	}
	return 0
}

// ResourceNode is a node in the topology graph.
type ResourceNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource reference
	Resource *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Node metadata
	NodeId   string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeType string `protobuf:"bytes,3,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	// Health status
	Health *HealthStatus `protobuf:"bytes,4,opt,name=health,proto3" json:"health,omitempty"`
	// Metrics summary
	Metrics       *ResourceMetrics `protobuf:"bytes,5,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceNode) Reset() {
	*x = ResourceNode{}
	mi := &file_cluster_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceNode) ProtoMessage() {}

func (x *ResourceNode) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceNode.ProtoReflect.Descriptor instead.
func (*ResourceNode) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{11}
}

func (x *ResourceNode) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ResourceNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ResourceNode) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *ResourceNode) GetHealth() *HealthStatus {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *ResourceNode) GetMetrics() *ResourceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Dependency represents an edge in the topology graph.
type Dependency struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceId       string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId       string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	DependencyType string                 `protobuf:"bytes,3,opt,name=dependency_type,json=dependencyType,proto3" json:"dependency_type,omitempty"` // "owns", "selects", "uses", "mounts", etc.
	Metadata       map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_cluster_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{12}
}

func (x *Dependency) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Dependency) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Dependency) GetDependencyType() string {
	if x != nil {
		return x.DependencyType
	}
	return ""
}

func (x *Dependency) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// HealthRequest requests cluster health information.
type HealthRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClusterId      string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	IncludeDetails bool                   `protobuf:"varint,2,opt,name=include_details,json=includeDetails,proto3" json:"include_details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_cluster_data_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{13}
}

func (x *HealthRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *HealthRequest) GetIncludeDetails() bool {
	if x != nil {
		return x.IncludeDetails
	}
	return false
}

// ClusterHealth represents overall cluster health.
type ClusterHealth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall status: "healthy", "degraded", "critical"
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Health score (0-100)
	Score int32 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	// Component health
	Components []*ComponentHealth `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty"`
	// Resource counts
	ResourceCounts *ResourceCounts `protobuf:"bytes,4,opt,name=resource_counts,json=resourceCounts,proto3" json:"resource_counts,omitempty"`
	// Recent issues
	Issues        []*HealthIssue `protobuf:"bytes,5,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterHealth) Reset() {
	*x = ClusterHealth{}
	mi := &file_cluster_data_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterHealth) ProtoMessage() {}

func (x *ClusterHealth) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterHealth.ProtoReflect.Descriptor instead.
func (*ClusterHealth) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{14}
}

func (x *ClusterHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ClusterHealth) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ClusterHealth) GetComponents() []*ComponentHealth {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *ClusterHealth) GetResourceCounts() *ResourceCounts {
	if x != nil {
		return x.ResourceCounts
	}
	return nil
}

func (x *ClusterHealth) GetIssues() []*HealthIssue {
	if x != nil {
		return x.Issues
	}
	return nil
}

// ComponentHealth represents health of a cluster component.
type ComponentHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentHealth) Reset() {
	*x = ComponentHealth{}
	mi := &file_cluster_data_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHealth) ProtoMessage() {}

func (x *ComponentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHealth.ProtoReflect.Descriptor instead.
func (*ComponentHealth) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{15}
}

func (x *ComponentHealth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ComponentHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HealthStatus represents resource health.
type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "healthy", "warning", "critical", "unknown"
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	LastCheck     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_cluster_data_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{16}
}

func (x *HealthStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *HealthStatus) GetLastCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheck
	}
	return nil
}

// ResourceCounts holds counts of resources by type.
type ResourceCounts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pods          int32                  `protobuf:"varint,1,opt,name=pods,proto3" json:"pods,omitempty"`
	Deployments   int32                  `protobuf:"varint,2,opt,name=deployments,proto3" json:"deployments,omitempty"`
	Services      int32                  `protobuf:"varint,3,opt,name=services,proto3" json:"services,omitempty"`
	Nodes         int32                  `protobuf:"varint,4,opt,name=nodes,proto3" json:"nodes,omitempty"`
	Namespaces    int32                  `protobuf:"varint,5,opt,name=namespaces,proto3" json:"namespaces,omitempty"`
	CustomCounts  map[string]int32       `protobuf:"bytes,6,rep,name=custom_counts,json=customCounts,proto3" json:"custom_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceCounts) Reset() {
	*x = ResourceCounts{}
	mi := &file_cluster_data_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceCounts) ProtoMessage() {}

func (x *ResourceCounts) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceCounts.ProtoReflect.Descriptor instead.
func (*ResourceCounts) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{17}
}

func (x *ResourceCounts) GetPods() int32 {
	if x != nil {
		return x.Pods
	}
	return 0
}

func (x *ResourceCounts) GetDeployments() int32 {
	if x != nil {
		return x.Deployments
	}
	return 0
}

func (x *ResourceCounts) GetServices() int32 {
	if x != nil {
		return x.Services
	}
	return 0
}

func (x *ResourceCounts) GetNodes() int32 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

func (x *ResourceCounts) GetNamespaces() int32 {
	if x != nil {
		return x.Namespaces
	}
	return 0
}

func (x *ResourceCounts) GetCustomCounts() map[string]int32 {
	if x != nil {
		return x.CustomCounts
	}
	return nil
}

// HealthIssue represents a health problem.
type HealthIssue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"` // "warning", "error", "critical"
	Component     string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	DetectedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthIssue) Reset() {
	*x = HealthIssue{}
	mi := &file_cluster_data_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthIssue) ProtoMessage() {}

func (x *HealthIssue) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthIssue.ProtoReflect.Descriptor instead.
func (*HealthIssue) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{18}
}

func (x *HealthIssue) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *HealthIssue) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *HealthIssue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthIssue) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

// MetricsRequest requests time-series metrics.
type MetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target resource
	Resource *ResourceRequest `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Metric names to retrieve
	MetricNames []string `protobuf:"bytes,2,rep,name=metric_names,json=metricNames,proto3" json:"metric_names,omitempty"`
	// Time range
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Resolution (e.g., "1m", "5m", "1h")
	Resolution    string `protobuf:"bytes,5,opt,name=resolution,proto3" json:"resolution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_cluster_data_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{19}
}

func (x *MetricsRequest) GetResource() *ResourceRequest {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *MetricsRequest) GetMetricNames() []string {
	if x != nil {
		return x.MetricNames
	}
	return nil
}

func (x *MetricsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *MetricsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *MetricsRequest) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

// MetricsResponse returns time-series metrics.
type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*MetricSeries        `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_cluster_data_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{20}
}

func (x *MetricsResponse) GetSeries() []*MetricSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

// MetricSeries is a time-series of metric values.
type MetricSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricName    string                 `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	Points        []*DataPoint           `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSeries) Reset() {
	*x = MetricSeries{}
	mi := &file_cluster_data_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSeries) ProtoMessage() {}

func (x *MetricSeries) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSeries.ProtoReflect.Descriptor instead.
func (*MetricSeries) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{21}
}

func (x *MetricSeries) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *MetricSeries) GetPoints() []*DataPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *MetricSeries) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

// DataPoint is a single metric data point.
type DataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_cluster_data_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{22}
}

func (x *DataPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// ResourceMetrics holds current resource metrics.
type ResourceMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`                // CPU usage (cores)
	MemoryUsage   float64                `protobuf:"fixed64,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`       // Memory usage (bytes)
	CpuRequest    float64                `protobuf:"fixed64,3,opt,name=cpu_request,json=cpuRequest,proto3" json:"cpu_request,omitempty"`          // CPU request (cores)
	MemoryRequest float64                `protobuf:"fixed64,4,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"` // Memory request (bytes)
	CpuLimit      float64                `protobuf:"fixed64,5,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`                // CPU limit (cores)
	MemoryLimit   float64                `protobuf:"fixed64,6,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`       // Memory limit (bytes)
	RestartCount  int32                  `protobuf:"varint,7,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`     // Number of restarts
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceMetrics) Reset() {
	*x = ResourceMetrics{}
	mi := &file_cluster_data_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMetrics) ProtoMessage() {}

func (x *ResourceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMetrics.ProtoReflect.Descriptor instead.
func (*ResourceMetrics) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{23}
}

func (x *ResourceMetrics) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ResourceMetrics) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *ResourceMetrics) GetCpuRequest() float64 {
	if x != nil {
		return x.CpuRequest
	}
	return 0
}

func (x *ResourceMetrics) GetMemoryRequest() float64 {
	if x != nil {
		return x.MemoryRequest
	}
	return 0
}

func (x *ResourceMetrics) GetCpuLimit() float64 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *ResourceMetrics) GetMemoryLimit() float64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *ResourceMetrics) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

// EventsRequest requests Kubernetes events.
type EventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target resource (optional)
	Resource *ResourceRequest `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Namespace filter
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Event type filter ("Normal", "Warning")
	EventType string `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Time range
	StartTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Limit
	Limit         int32 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsRequest) Reset() {
	*x = EventsRequest{}
	mi := &file_cluster_data_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest) ProtoMessage() {}

func (x *EventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest.ProtoReflect.Descriptor instead.
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{24}
}

func (x *EventsRequest) GetResource() *ResourceRequest {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *EventsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EventsRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *EventsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *EventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// EventsResponse returns Kubernetes events.
type EventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*KubernetesEvent     `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsResponse) Reset() {
	*x = EventsResponse{}
	mi := &file_cluster_data_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse) ProtoMessage() {}

func (x *EventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse.ProtoReflect.Descriptor instead.
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{25}
}

func (x *EventsResponse) GetEvents() []*KubernetesEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// KubernetesEvent represents a Kubernetes event.
type KubernetesEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "Normal" or "Warning"
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	InvolvedObject *ResourceRequest       `protobuf:"bytes,4,opt,name=involved_object,json=involvedObject,proto3" json:"involved_object,omitempty"`
	FirstTimestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=first_timestamp,json=firstTimestamp,proto3" json:"first_timestamp,omitempty"`
	LastTimestamp  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_timestamp,json=lastTimestamp,proto3" json:"last_timestamp,omitempty"`
	Count          int32                  `protobuf:"varint,7,opt,name=count,proto3" json:"count,omitempty"`
	Source         string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KubernetesEvent) Reset() {
	*x = KubernetesEvent{}
	mi := &file_cluster_data_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesEvent) ProtoMessage() {}

func (x *KubernetesEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_data_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesEvent.ProtoReflect.Descriptor instead.
func (*KubernetesEvent) Descriptor() ([]byte, []int) {
	return file_cluster_data_proto_rawDescGZIP(), []int{26}
}

func (x *KubernetesEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *KubernetesEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *KubernetesEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *KubernetesEvent) GetInvolvedObject() *ResourceRequest {
	if x != nil {
		return x.InvolvedObject
	}
	return nil
}

func (x *KubernetesEvent) GetFirstTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstTimestamp
	}
	return nil
}

func (x *KubernetesEvent) GetLastTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTimestamp
	}
	return nil
}

func (x *KubernetesEvent) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *KubernetesEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_cluster_data_proto protoreflect.FileDescriptor

const file_cluster_data_proto_rawDesc = "" +
	"\n" +
	"\x12cluster_data.proto\x12\x10kubilitics.ai.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x02\n" +
	"\x12StateStreamRequest\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespaces\x12%\n" +
	"\x0eresource_kinds\x18\x02 \x03(\tR\rresourceKinds\x12^\n" +
	"\x0elabel_selector\x18\x03 \x03(\v27.kubilitics.ai.v1.StateStreamRequest.LabelSelectorEntryR\rlabelSelector\x12)\n" +
	"\x10include_snapshot\x18\x04 \x01(\bR\x0fincludeSnapshot\x1a@\n" +
	"\x12LabelSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x01\n" +
	"\vStateUpdate\x12\x1f\n" +
	"\vupdate_type\x18\x01 \x01(\tR\n" +
	"updateType\x126\n" +
	"\bresource\x18\x02 \x01(\v2\x1a.kubilitics.ai.v1.ResourceR\bresource\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x03R\bsequence\"v\n" +
	"\x0fResourceRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x04 \x01(\tR\tclusterId\"\xe0\x04\n" +
	"\bResource\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\tR\x03uid\x12)\n" +
	"\x10resource_version\x18\x06 \x01(\tR\x0fresourceVersion\x12>\n" +
	"\x06labels\x18\a \x03(\v2&.kubilitics.ai.v1.Resource.LabelsEntryR\x06labels\x12M\n" +
	"\vannotations\x18\b \x03(\v2+.kubilitics.ai.v1.Resource.AnnotationsEntryR\vannotations\x12\x12\n" +
	"\x04data\x18\t \x01(\fR\x04data\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12?\n" +
	"\n" +
	"owner_refs\x18\f \x03(\v2 .kubilitics.ai.v1.OwnerReferenceR\townerRefs\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x0eOwnerReference\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uid\x12\x1e\n" +
	"\n" +
	"controller\x18\x04 \x01(\bR\n" +
	"controller\"\xd1\x03\n" +
	"\vListRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12W\n" +
	"\x0elabel_selector\x18\x03 \x03(\v20.kubilitics.ai.v1.ListRequest.LabelSelectorEntryR\rlabelSelector\x12W\n" +
	"\x0efield_selector\x18\x04 \x03(\v20.kubilitics.ai.v1.ListRequest.FieldSelectorEntryR\rfieldSelector\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x05 \x01(\tR\tclusterId\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12%\n" +
	"\x0econtinue_token\x18\a \x01(\tR\rcontinueToken\x1a@\n" +
	"\x12LabelSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12FieldSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x01\n" +
	"\fResourceList\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.kubilitics.ai.v1.ResourceR\x05items\x12%\n" +
	"\x0econtinue_token\x18\x02 \x01(\tR\rcontinueToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xba\x01\n" +
	"\x0eCommandRequest\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x122\n" +
	"\x06target\x18\x02 \x01(\v2\x1a.kubilitics.ai.v1.ResourceR\x06target\x12\x16\n" +
	"\x06params\x18\x03 \x01(\fR\x06params\x12\x17\n" +
	"\adry_run\x18\x04 \x01(\bR\x06dryRun\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\"\xc7\x01\n" +
	"\rCommandResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12E\n" +
	"\x10updated_resource\x18\x04 \x01(\v2\x1a.kubilitics.ai.v1.ResourceR\x0fupdatedResource\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\"\xa2\x01\n" +
	"\x0fTopologyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x125\n" +
	"\x04root\x18\x02 \x01(\v2!.kubilitics.ai.v1.ResourceRequestR\x04root\x12\x1b\n" +
	"\tmax_depth\x18\x03 \x01(\x05R\bmaxDepth\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x04 \x01(\tR\tclusterId\"\xbb\x01\n" +
	"\rTopologyGraph\x124\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1e.kubilitics.ai.v1.ResourceNodeR\x05nodes\x122\n" +
	"\x05edges\x18\x02 \x03(\v2\x1c.kubilitics.ai.v1.DependencyR\x05edges\x12\x1f\n" +
	"\vtotal_nodes\x18\x03 \x01(\x05R\n" +
	"totalNodes\x12\x1f\n" +
	"\vtotal_edges\x18\x04 \x01(\x05R\n" +
	"totalEdges\"\xf1\x01\n" +
	"\fResourceNode\x126\n" +
	"\bresource\x18\x01 \x01(\v2\x1a.kubilitics.ai.v1.ResourceR\bresource\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_type\x18\x03 \x01(\tR\bnodeType\x126\n" +
	"\x06health\x18\x04 \x01(\v2\x1e.kubilitics.ai.v1.HealthStatusR\x06health\x12;\n" +
	"\ametrics\x18\x05 \x01(\v2!.kubilitics.ai.v1.ResourceMetricsR\ametrics\"\xf4\x01\n" +
	"\n" +
	"Dependency\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12'\n" +
	"\x0fdependency_type\x18\x03 \x01(\tR\x0edependencyType\x12F\n" +
	"\bmetadata\x18\x04 \x03(\v2*.kubilitics.ai.v1.Dependency.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\rHealthRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12'\n" +
	"\x0finclude_details\x18\x02 \x01(\bR\x0eincludeDetails\"\x82\x02\n" +
	"\rClusterHealth\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12A\n" +
	"\n" +
	"components\x18\x03 \x03(\v2!.kubilitics.ai.v1.ComponentHealthR\n" +
	"components\x12I\n" +
	"\x0fresource_counts\x18\x04 \x01(\v2 .kubilitics.ai.v1.ResourceCountsR\x0eresourceCounts\x125\n" +
	"\x06issues\x18\x05 \x03(\v2\x1d.kubilitics.ai.v1.HealthIssueR\x06issues\"W\n" +
	"\x0fComponentHealth\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"y\n" +
	"\fHealthStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"last_check\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tlastCheck\"\xb2\x02\n" +
	"\x0eResourceCounts\x12\x12\n" +
	"\x04pods\x18\x01 \x01(\x05R\x04pods\x12 \n" +
	"\vdeployments\x18\x02 \x01(\x05R\vdeployments\x12\x1a\n" +
	"\bservices\x18\x03 \x01(\x05R\bservices\x12\x14\n" +
	"\x05nodes\x18\x04 \x01(\x05R\x05nodes\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x05 \x01(\x05R\n" +
	"namespaces\x12W\n" +
	"\rcustom_counts\x18\x06 \x03(\v22.kubilitics.ai.v1.ResourceCounts.CustomCountsEntryR\fcustomCounts\x1a?\n" +
	"\x11CustomCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x9e\x01\n" +
	"\vHealthIssue\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12;\n" +
	"\vdetected_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAt\"\x84\x02\n" +
	"\x0eMetricsRequest\x12=\n" +
	"\bresource\x18\x01 \x01(\v2!.kubilitics.ai.v1.ResourceRequestR\bresource\x12!\n" +
	"\fmetric_names\x18\x02 \x03(\tR\vmetricNames\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1e\n" +
	"\n" +
	"resolution\x18\x05 \x01(\tR\n" +
	"resolution\"I\n" +
	"\x0fMetricsResponse\x126\n" +
	"\x06series\x18\x01 \x03(\v2\x1e.kubilitics.ai.v1.MetricSeriesR\x06series\"x\n" +
	"\fMetricSeries\x12\x1f\n" +
	"\vmetric_name\x18\x01 \x01(\tR\n" +
	"metricName\x123\n" +
	"\x06points\x18\x02 \x03(\v2\x1b.kubilitics.ai.v1.DataPointR\x06points\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\"[\n" +
	"\tDataPoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\xfe\x01\n" +
	"\x0fResourceMetrics\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x01R\vmemoryUsage\x12\x1f\n" +
	"\vcpu_request\x18\x03 \x01(\x01R\n" +
	"cpuRequest\x12%\n" +
	"\x0ememory_request\x18\x04 \x01(\x01R\rmemoryRequest\x12\x1b\n" +
	"\tcpu_limit\x18\x05 \x01(\x01R\bcpuLimit\x12!\n" +
	"\fmemory_limit\x18\x06 \x01(\x01R\vmemoryLimit\x12#\n" +
	"\rrestart_count\x18\a \x01(\x05R\frestartCount\"\x93\x02\n" +
	"\rEventsRequest\x12=\n" +
	"\bresource\x18\x01 \x01(\v2!.kubilitics.ai.v1.ResourceRequestR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"K\n" +
	"\x0eEventsResponse\x129\n" +
	"\x06events\x18\x01 \x03(\v2!.kubilitics.ai.v1.KubernetesEventR\x06events\"\xd9\x02\n" +
	"\x0fKubernetesEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12J\n" +
	"\x0finvolved_object\x18\x04 \x01(\v2!.kubilitics.ai.v1.ResourceRequestR\x0einvolvedObject\x12C\n" +
	"\x0ffirst_timestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0efirstTimestamp\x12A\n" +
	"\x0elast_timestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rlastTimestamp\x12\x14\n" +
	"\x05count\x18\a \x01(\x05R\x05count\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source2\xb5\x05\n" +
	"\x12ClusterDataService\x12[\n" +
	"\x12StreamClusterState\x12$.kubilitics.ai.v1.StateStreamRequest\x1a\x1d.kubilitics.ai.v1.StateUpdate0\x01\x12L\n" +
	"\vGetResource\x12!.kubilitics.ai.v1.ResourceRequest\x1a\x1a.kubilitics.ai.v1.Resource\x12N\n" +
	"\rListResources\x12\x1d.kubilitics.ai.v1.ListRequest\x1a\x1e.kubilitics.ai.v1.ResourceList\x12S\n" +
	"\x0eExecuteCommand\x12 .kubilitics.ai.v1.CommandRequest\x1a\x1f.kubilitics.ai.v1.CommandResult\x12V\n" +
	"\x10GetTopologyGraph\x12!.kubilitics.ai.v1.TopologyRequest\x1a\x1f.kubilitics.ai.v1.TopologyGraph\x12T\n" +
	"\x10GetClusterHealth\x12\x1f.kubilitics.ai.v1.HealthRequest\x1a\x1f.kubilitics.ai.v1.ClusterHealth\x12Q\n" +
	"\n" +
	"GetMetrics\x12 .kubilitics.ai.v1.MetricsRequest\x1a!.kubilitics.ai.v1.MetricsResponse\x12N\n" +
	"\tGetEvents\x12\x1f.kubilitics.ai.v1.EventsRequest\x1a .kubilitics.ai.v1.EventsResponseB5Z3github.com/kubilitics/kubilitics-ai/api/proto/v1;v1b\x06proto3"

var (
	file_cluster_data_proto_rawDescOnce sync.Once
	file_cluster_data_proto_rawDescData []byte
)

func file_cluster_data_proto_rawDescGZIP() []byte {
	file_cluster_data_proto_rawDescOnce.Do(func() {
		file_cluster_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_data_proto_rawDesc), len(file_cluster_data_proto_rawDesc)))
	})
	return file_cluster_data_proto_rawDescData
}

var file_cluster_data_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_cluster_data_proto_goTypes = []any{
	(*StateStreamRequest)(nil),    // 0: kubilitics.ai.v1.StateStreamRequest
	(*StateUpdate)(nil),           // 1: kubilitics.ai.v1.StateUpdate
	(*ResourceRequest)(nil),       // 2: kubilitics.ai.v1.ResourceRequest
	(*Resource)(nil),              // 3: kubilitics.ai.v1.Resource
	(*OwnerReference)(nil),        // 4: kubilitics.ai.v1.OwnerReference
	(*ListRequest)(nil),           // 5: kubilitics.ai.v1.ListRequest
	(*ResourceList)(nil),          // 6: kubilitics.ai.v1.ResourceList
	(*CommandRequest)(nil),        // 7: kubilitics.ai.v1.CommandRequest
	(*CommandResult)(nil),         // 8: kubilitics.ai.v1.CommandResult
	(*TopologyRequest)(nil),       // 9: kubilitics.ai.v1.TopologyRequest
	(*TopologyGraph)(nil),         // 10: kubilitics.ai.v1.TopologyGraph
	(*ResourceNode)(nil),          // 11: kubilitics.ai.v1.ResourceNode
	(*Dependency)(nil),            // 12: kubilitics.ai.v1.Dependency
	(*HealthRequest)(nil),         // 13: kubilitics.ai.v1.HealthRequest
	(*ClusterHealth)(nil),         // 14: kubilitics.ai.v1.ClusterHealth
	(*ComponentHealth)(nil),       // 15: kubilitics.ai.v1.ComponentHealth
	(*HealthStatus)(nil),          // 16: kubilitics.ai.v1.HealthStatus
	(*ResourceCounts)(nil),        // 17: kubilitics.ai.v1.ResourceCounts
	(*HealthIssue)(nil),           // 18: kubilitics.ai.v1.HealthIssue
	(*MetricsRequest)(nil),        // 19: kubilitics.ai.v1.MetricsRequest
	(*MetricsResponse)(nil),       // 20: kubilitics.ai.v1.MetricsResponse
	(*MetricSeries)(nil),          // 21: kubilitics.ai.v1.MetricSeries
	(*DataPoint)(nil),             // 22: kubilitics.ai.v1.DataPoint
	(*ResourceMetrics)(nil),       // 23: kubilitics.ai.v1.ResourceMetrics
	(*EventsRequest)(nil),         // 24: kubilitics.ai.v1.EventsRequest
	(*EventsResponse)(nil),        // 25: kubilitics.ai.v1.EventsResponse
	(*KubernetesEvent)(nil),       // 26: kubilitics.ai.v1.KubernetesEvent
	nil,                           // 27: kubilitics.ai.v1.StateStreamRequest.LabelSelectorEntry
	nil,                           // 28: kubilitics.ai.v1.Resource.LabelsEntry
	nil,                           // 29: kubilitics.ai.v1.Resource.AnnotationsEntry
	nil,                           // 30: kubilitics.ai.v1.ListRequest.LabelSelectorEntry
	nil,                           // 31: kubilitics.ai.v1.ListRequest.FieldSelectorEntry
	nil,                           // 32: kubilitics.ai.v1.Dependency.MetadataEntry
	nil,                           // 33: kubilitics.ai.v1.ResourceCounts.CustomCountsEntry
	(*timestamppb.Timestamp)(nil), // 34: google.protobuf.Timestamp
}
var file_cluster_data_proto_depIdxs = []int32{
	27, // 0: kubilitics.ai.v1.StateStreamRequest.label_selector:type_name -> kubilitics.ai.v1.StateStreamRequest.LabelSelectorEntry
	3,  // 1: kubilitics.ai.v1.StateUpdate.resource:type_name -> kubilitics.ai.v1.Resource
	34, // 2: kubilitics.ai.v1.StateUpdate.timestamp:type_name -> google.protobuf.Timestamp
	28, // 3: kubilitics.ai.v1.Resource.labels:type_name -> kubilitics.ai.v1.Resource.LabelsEntry
	29, // 4: kubilitics.ai.v1.Resource.annotations:type_name -> kubilitics.ai.v1.Resource.AnnotationsEntry
	34, // 5: kubilitics.ai.v1.Resource.created_at:type_name -> google.protobuf.Timestamp
	4,  // 6: kubilitics.ai.v1.Resource.owner_refs:type_name -> kubilitics.ai.v1.OwnerReference
	30, // 7: kubilitics.ai.v1.ListRequest.label_selector:type_name -> kubilitics.ai.v1.ListRequest.LabelSelectorEntry
	31, // 8: kubilitics.ai.v1.ListRequest.field_selector:type_name -> kubilitics.ai.v1.ListRequest.FieldSelectorEntry
	3,  // 9: kubilitics.ai.v1.ResourceList.items:type_name -> kubilitics.ai.v1.Resource
	3,  // 10: kubilitics.ai.v1.CommandRequest.target:type_name -> kubilitics.ai.v1.Resource
	3,  // 11: kubilitics.ai.v1.CommandResult.updated_resource:type_name -> kubilitics.ai.v1.Resource
	2,  // 12: kubilitics.ai.v1.TopologyRequest.root:type_name -> kubilitics.ai.v1.ResourceRequest
	11, // 13: kubilitics.ai.v1.TopologyGraph.nodes:type_name -> kubilitics.ai.v1.ResourceNode
	12, // 14: kubilitics.ai.v1.TopologyGraph.edges:type_name -> kubilitics.ai.v1.Dependency
	3,  // 15: kubilitics.ai.v1.ResourceNode.resource:type_name -> kubilitics.ai.v1.Resource
	16, // 16: kubilitics.ai.v1.ResourceNode.health:type_name -> kubilitics.ai.v1.HealthStatus
	23, // 17: kubilitics.ai.v1.ResourceNode.metrics:type_name -> kubilitics.ai.v1.ResourceMetrics
	32, // 18: kubilitics.ai.v1.Dependency.metadata:type_name -> kubilitics.ai.v1.Dependency.MetadataEntry
	15, // 19: kubilitics.ai.v1.ClusterHealth.components:type_name -> kubilitics.ai.v1.ComponentHealth
	17, // 20: kubilitics.ai.v1.ClusterHealth.resource_counts:type_name -> kubilitics.ai.v1.ResourceCounts
	18, // 21: kubilitics.ai.v1.ClusterHealth.issues:type_name -> kubilitics.ai.v1.HealthIssue
	34, // 22: kubilitics.ai.v1.HealthStatus.last_check:type_name -> google.protobuf.Timestamp
	33, // 23: kubilitics.ai.v1.ResourceCounts.custom_counts:type_name -> kubilitics.ai.v1.ResourceCounts.CustomCountsEntry
	34, // 24: kubilitics.ai.v1.HealthIssue.detected_at:type_name -> google.protobuf.Timestamp
	2,  // 25: kubilitics.ai.v1.MetricsRequest.resource:type_name -> kubilitics.ai.v1.ResourceRequest
	34, // 26: kubilitics.ai.v1.MetricsRequest.start_time:type_name -> google.protobuf.Timestamp
	34, // 27: kubilitics.ai.v1.MetricsRequest.end_time:type_name -> google.protobuf.Timestamp
	21, // 28: kubilitics.ai.v1.MetricsResponse.series:type_name -> kubilitics.ai.v1.MetricSeries
	22, // 29: kubilitics.ai.v1.MetricSeries.points:type_name -> kubilitics.ai.v1.DataPoint
	34, // 30: kubilitics.ai.v1.DataPoint.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 31: kubilitics.ai.v1.EventsRequest.resource:type_name -> kubilitics.ai.v1.ResourceRequest
	34, // 32: kubilitics.ai.v1.EventsRequest.start_time:type_name -> google.protobuf.Timestamp
	34, // 33: kubilitics.ai.v1.EventsRequest.end_time:type_name -> google.protobuf.Timestamp
	26, // 34: kubilitics.ai.v1.EventsResponse.events:type_name -> kubilitics.ai.v1.KubernetesEvent
	2,  // 35: kubilitics.ai.v1.KubernetesEvent.involved_object:type_name -> kubilitics.ai.v1.ResourceRequest
	34, // 36: kubilitics.ai.v1.KubernetesEvent.first_timestamp:type_name -> google.protobuf.Timestamp
	34, // 37: kubilitics.ai.v1.KubernetesEvent.last_timestamp:type_name -> google.protobuf.Timestamp
	0,  // 38: kubilitics.ai.v1.ClusterDataService.StreamClusterState:input_type -> kubilitics.ai.v1.StateStreamRequest
	2,  // 39: kubilitics.ai.v1.ClusterDataService.GetResource:input_type -> kubilitics.ai.v1.ResourceRequest
	5,  // 40: kubilitics.ai.v1.ClusterDataService.ListResources:input_type -> kubilitics.ai.v1.ListRequest
	7,  // 41: kubilitics.ai.v1.ClusterDataService.ExecuteCommand:input_type -> kubilitics.ai.v1.CommandRequest
	9,  // 42: kubilitics.ai.v1.ClusterDataService.GetTopologyGraph:input_type -> kubilitics.ai.v1.TopologyRequest
	13, // 43: kubilitics.ai.v1.ClusterDataService.GetClusterHealth:input_type -> kubilitics.ai.v1.HealthRequest
	19, // 44: kubilitics.ai.v1.ClusterDataService.GetMetrics:input_type -> kubilitics.ai.v1.MetricsRequest
	24, // 45: kubilitics.ai.v1.ClusterDataService.GetEvents:input_type -> kubilitics.ai.v1.EventsRequest
	1,  // 46: kubilitics.ai.v1.ClusterDataService.StreamClusterState:output_type -> kubilitics.ai.v1.StateUpdate
	3,  // 47: kubilitics.ai.v1.ClusterDataService.GetResource:output_type -> kubilitics.ai.v1.Resource
	6,  // 48: kubilitics.ai.v1.ClusterDataService.ListResources:output_type -> kubilitics.ai.v1.ResourceList
	8,  // 49: kubilitics.ai.v1.ClusterDataService.ExecuteCommand:output_type -> kubilitics.ai.v1.CommandResult
	10, // 50: kubilitics.ai.v1.ClusterDataService.GetTopologyGraph:output_type -> kubilitics.ai.v1.TopologyGraph
	14, // 51: kubilitics.ai.v1.ClusterDataService.GetClusterHealth:output_type -> kubilitics.ai.v1.ClusterHealth
	20, // 52: kubilitics.ai.v1.ClusterDataService.GetMetrics:output_type -> kubilitics.ai.v1.MetricsResponse
	25, // 53: kubilitics.ai.v1.ClusterDataService.GetEvents:output_type -> kubilitics.ai.v1.EventsResponse
	46, // [46:54] is the sub-list for method output_type
	38, // [38:46] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_cluster_data_proto_init() }
func file_cluster_data_proto_init() {
	if File_cluster_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_data_proto_rawDesc), len(file_cluster_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cluster_data_proto_goTypes,
		DependencyIndexes: file_cluster_data_proto_depIdxs,
		MessageInfos:      file_cluster_data_proto_msgTypes,
	}.Build()
	File_cluster_data_proto = out.File
	file_cluster_data_proto_goTypes = nil
	file_cluster_data_proto_depIdxs = nil
}
