// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: cluster_data.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterDataService_StreamClusterState_FullMethodName = "/kubilitics.ai.v1.ClusterDataService/StreamClusterState"
	ClusterDataService_GetResource_FullMethodName        = "/kubilitics.ai.v1.ClusterDataService/GetResource"
	ClusterDataService_ListResources_FullMethodName      = "/kubilitics.ai.v1.ClusterDataService/ListResources"
	ClusterDataService_ExecuteCommand_FullMethodName     = "/kubilitics.ai.v1.ClusterDataService/ExecuteCommand"
	ClusterDataService_GetTopologyGraph_FullMethodName   = "/kubilitics.ai.v1.ClusterDataService/GetTopologyGraph"
	ClusterDataService_GetClusterHealth_FullMethodName   = "/kubilitics.ai.v1.ClusterDataService/GetClusterHealth"
	ClusterDataService_GetMetrics_FullMethodName         = "/kubilitics.ai.v1.ClusterDataService/GetMetrics"
	ClusterDataService_GetEvents_FullMethodName          = "/kubilitics.ai.v1.ClusterDataService/GetEvents"
)

// ClusterDataServiceClient is the client API for ClusterDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClusterDataService defines the gRPC service for kubilitics-ai to consume
// cluster state from kubilitics-backend.
type ClusterDataServiceClient interface {
	// StreamClusterState streams real-time cluster state updates.
	// This is the primary method for keeping the World Model synchronized.
	StreamClusterState(ctx context.Context, in *StateStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateUpdate], error)
	// GetResource retrieves a specific Kubernetes resource by kind/namespace/name.
	GetResource(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*Resource, error)
	// ListResources lists resources of a given kind with optional filtering.
	ListResources(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ResourceList, error)
	// ExecuteCommand executes a command against a resource (e.g., restart pod).
	// This is used by the action execution system.
	ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResult, error)
	// GetTopologyGraph retrieves the full topology graph for visualization.
	GetTopologyGraph(ctx context.Context, in *TopologyRequest, opts ...grpc.CallOption) (*TopologyGraph, error)
	// GetClusterHealth retrieves overall cluster health metrics.
	GetClusterHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*ClusterHealth, error)
	// GetMetrics retrieves time-series metrics for resources.
	GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error)
	// GetEvents retrieves Kubernetes events for a resource or namespace.
	GetEvents(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (*EventsResponse, error)
}

type clusterDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterDataServiceClient(cc grpc.ClientConnInterface) ClusterDataServiceClient {
	return &clusterDataServiceClient{cc}
}

func (c *clusterDataServiceClient) StreamClusterState(ctx context.Context, in *StateStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClusterDataService_ServiceDesc.Streams[0], ClusterDataService_StreamClusterState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StateStreamRequest, StateUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterDataService_StreamClusterStateClient = grpc.ServerStreamingClient[StateUpdate]

func (c *clusterDataServiceClient) GetResource(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*Resource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Resource)
	err := c.cc.Invoke(ctx, ClusterDataService_GetResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterDataServiceClient) ListResources(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ResourceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourceList)
	err := c.cc.Invoke(ctx, ClusterDataService_ListResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterDataServiceClient) ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, ClusterDataService_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterDataServiceClient) GetTopologyGraph(ctx context.Context, in *TopologyRequest, opts ...grpc.CallOption) (*TopologyGraph, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopologyGraph)
	err := c.cc.Invoke(ctx, ClusterDataService_GetTopologyGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterDataServiceClient) GetClusterHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*ClusterHealth, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterHealth)
	err := c.cc.Invoke(ctx, ClusterDataService_GetClusterHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterDataServiceClient) GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, ClusterDataService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterDataServiceClient) GetEvents(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (*EventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventsResponse)
	err := c.cc.Invoke(ctx, ClusterDataService_GetEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterDataServiceServer is the server API for ClusterDataService service.
// All implementations must embed UnimplementedClusterDataServiceServer
// for forward compatibility.
//
// ClusterDataService defines the gRPC service for kubilitics-ai to consume
// cluster state from kubilitics-backend.
type ClusterDataServiceServer interface {
	// StreamClusterState streams real-time cluster state updates.
	// This is the primary method for keeping the World Model synchronized.
	StreamClusterState(*StateStreamRequest, grpc.ServerStreamingServer[StateUpdate]) error
	// GetResource retrieves a specific Kubernetes resource by kind/namespace/name.
	GetResource(context.Context, *ResourceRequest) (*Resource, error)
	// ListResources lists resources of a given kind with optional filtering.
	ListResources(context.Context, *ListRequest) (*ResourceList, error)
	// ExecuteCommand executes a command against a resource (e.g., restart pod).
	// This is used by the action execution system.
	ExecuteCommand(context.Context, *CommandRequest) (*CommandResult, error)
	// GetTopologyGraph retrieves the full topology graph for visualization.
	GetTopologyGraph(context.Context, *TopologyRequest) (*TopologyGraph, error)
	// GetClusterHealth retrieves overall cluster health metrics.
	GetClusterHealth(context.Context, *HealthRequest) (*ClusterHealth, error)
	// GetMetrics retrieves time-series metrics for resources.
	GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error)
	// GetEvents retrieves Kubernetes events for a resource or namespace.
	GetEvents(context.Context, *EventsRequest) (*EventsResponse, error)
	mustEmbedUnimplementedClusterDataServiceServer()
}

// UnimplementedClusterDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterDataServiceServer struct{}

func (UnimplementedClusterDataServiceServer) StreamClusterState(*StateStreamRequest, grpc.ServerStreamingServer[StateUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamClusterState not implemented")
}
func (UnimplementedClusterDataServiceServer) GetResource(context.Context, *ResourceRequest) (*Resource, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResource not implemented")
}
func (UnimplementedClusterDataServiceServer) ListResources(context.Context, *ListRequest) (*ResourceList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResources not implemented")
}
func (UnimplementedClusterDataServiceServer) ExecuteCommand(context.Context, *CommandRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedClusterDataServiceServer) GetTopologyGraph(context.Context, *TopologyRequest) (*TopologyGraph, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopologyGraph not implemented")
}
func (UnimplementedClusterDataServiceServer) GetClusterHealth(context.Context, *HealthRequest) (*ClusterHealth, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterHealth not implemented")
}
func (UnimplementedClusterDataServiceServer) GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedClusterDataServiceServer) GetEvents(context.Context, *EventsRequest) (*EventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedClusterDataServiceServer) mustEmbedUnimplementedClusterDataServiceServer() {}
func (UnimplementedClusterDataServiceServer) testEmbeddedByValue()                            {}

// UnsafeClusterDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterDataServiceServer will
// result in compilation errors.
type UnsafeClusterDataServiceServer interface {
	mustEmbedUnimplementedClusterDataServiceServer()
}

func RegisterClusterDataServiceServer(s grpc.ServiceRegistrar, srv ClusterDataServiceServer) {
	// If the following call panics, it indicates UnimplementedClusterDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterDataService_ServiceDesc, srv)
}

func _ClusterDataService_StreamClusterState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StateStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClusterDataServiceServer).StreamClusterState(m, &grpc.GenericServerStream[StateStreamRequest, StateUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterDataService_StreamClusterStateServer = grpc.ServerStreamingServer[StateUpdate]

func _ClusterDataService_GetResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterDataServiceServer).GetResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterDataService_GetResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterDataServiceServer).GetResource(ctx, req.(*ResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterDataService_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterDataServiceServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterDataService_ListResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterDataServiceServer).ListResources(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterDataService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterDataServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterDataService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterDataServiceServer).ExecuteCommand(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterDataService_GetTopologyGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterDataServiceServer).GetTopologyGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterDataService_GetTopologyGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterDataServiceServer).GetTopologyGraph(ctx, req.(*TopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterDataService_GetClusterHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterDataServiceServer).GetClusterHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterDataService_GetClusterHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterDataServiceServer).GetClusterHealth(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterDataService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterDataServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterDataService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterDataServiceServer).GetMetrics(ctx, req.(*MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterDataService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterDataServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterDataService_GetEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterDataServiceServer).GetEvents(ctx, req.(*EventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterDataService_ServiceDesc is the grpc.ServiceDesc for ClusterDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kubilitics.ai.v1.ClusterDataService",
	HandlerType: (*ClusterDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetResource",
			Handler:    _ClusterDataService_GetResource_Handler,
		},
		{
			MethodName: "ListResources",
			Handler:    _ClusterDataService_ListResources_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _ClusterDataService_ExecuteCommand_Handler,
		},
		{
			MethodName: "GetTopologyGraph",
			Handler:    _ClusterDataService_GetTopologyGraph_Handler,
		},
		{
			MethodName: "GetClusterHealth",
			Handler:    _ClusterDataService_GetClusterHealth_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _ClusterDataService_GetMetrics_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _ClusterDataService_GetEvents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamClusterState",
			Handler:       _ClusterDataService_StreamClusterState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cluster_data.proto",
}
