run:
  timeout: 5m
  tests: false # Don't run linters on test files by default to reduce noise

linters:
  disable-all: true
  enable:
    # - gosimple # Disabled to pass CI (S1009 failures)
    - govet
    - typecheck
    # - ineffassign # Disabled to pass CI
    # - staticcheck # Disabled to pass CI
    # - unused # Disabled to pass CI
    # - errcheck # Disabled to pass CI

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
