# Demo CronJobs for Kubilitics (3-10 objects). Apply after namespace.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cron-backup
  namespace: kubilitics-demo
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: busybox:1.36
              command: ["echo", "backup run"]
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cron-cleanup
  namespace: kubilitics-demo
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cleanup
              image: busybox:1.36
              command: ["echo", "cleanup run"]
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cron-report
  namespace: kubilitics-demo
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
spec:
  schedule: "0 8 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: report
              image: busybox:1.36
              command: ["echo", "report run"]
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cron-sync
  namespace: kubilitics-demo
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: sync
              image: busybox:1.36
              command: ["echo", "sync run"]
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cron-health
  namespace: kubilitics-demo
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: health
              image: busybox:1.36
              command: ["echo", "health check"]
