# Demo StatefulSets for Kubilitics (3-10 objects). Apply after namespace.
# Headless services required by StatefulSets (serviceName)
apiVersion: v1
kind: Service
metadata:
  name: demo-db
  namespace: kubilitics-demo
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
spec:
  clusterIP: None
  selector:
    app: demo-db
  ports:
    - port: 6379
      name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: demo-cache
  namespace: kubilitics-demo
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
spec:
  clusterIP: None
  selector:
    app: demo-cache
  ports:
    - port: 6379
      name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: demo-queue
  namespace: kubilitics-demo
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
spec:
  clusterIP: None
  selector:
    app: demo-queue
  ports:
    - port: 6379
      name: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-db
  namespace: kubilitics-demo
  labels:
    app: demo-db
    app.kubernetes.io/part-of: kubilitics-demo
spec:
  serviceName: demo-db
  replicas: 2
  selector:
    matchLabels:
      app: demo-db
  template:
    metadata:
      labels:
        app: demo-db
        app.kubernetes.io/part-of: kubilitics-demo
    spec:
      containers:
        - name: db
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-cache
  namespace: kubilitics-demo
  labels:
    app: demo-cache
    app.kubernetes.io/part-of: kubilitics-demo
spec:
  serviceName: demo-cache
  replicas: 2
  selector:
    matchLabels:
      app: demo-cache
  template:
    metadata:
      labels:
        app: demo-cache
        app.kubernetes.io/part-of: kubilitics-demo
    spec:
      containers:
        - name: cache
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-queue
  namespace: kubilitics-demo
  labels:
    app: demo-queue
    app.kubernetes.io/part-of: kubilitics-demo
spec:
  serviceName: demo-queue
  replicas: 1
  selector:
    matchLabels:
      app: demo-queue
  template:
    metadata:
      labels:
        app: demo-queue
        app.kubernetes.io/part-of: kubilitics-demo
    spec:
      containers:
        - name: queue
          image: redis:7-alpine
          ports:
            - containerPort: 6379
